GameHunter/urls.py
from django.contrib import admin # type: ignore
from django.urls import include, path # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Hage.urls')),
]

Hage/urls.py
from django.urls import path # type: ignore
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.mostrar, name='index'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('contacto/', views.contacto, name='contacto'),
    path('login/', views.user_login, name='login'),
    path('registro/', views.registro, name='register'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('carrito/', views.carritos, name='carrito'),
    path('pago/', views.pago, name='pago'),
    path('crud/', views.producto_list, name='crud'),
    path('logout/', views.salir, name='logout'),
    path('modificar_producto/<int:id>', views.modificar, name='modificar_producto'),
    path('eliminar_producto/<int:id>', views.eliminar, name='eliminar_producto'),
    path('Producto/', views.mostrar, name='index'),
]

Hage/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.
class usuarios(models.Model):
    username = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    rol = models.CharField(max_length=20, choices=settings.ROLES)
    
    def __str__(self):
        return self.name


class categorias(models.Model):
    name = models.CharField(max_length=100)
    activate = models.BooleanField(default=True) # En caso de que la categoria no este disponible
    
    def __str__(self):
        return self.name
    
    
class productos(models.Model):
    name = models.CharField(max_length=100)
    categoria = models.ForeignKey('categorias', on_delete=models.CASCADE)
    precio = models.IntegerField(default=0)
    imagen = models.CharField(max_length=1000) # Guardar imagen en nube y guardar url
    activate = models.BooleanField(default=True) # En caso de que el producto no este disponible
    destacado = models.BooleanField(default=False) # Mostrar en la pagina principal
    
    def __str__(self):
        return self.name
    
class carrito(models.Model):
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.cantidad + ' ' + self.producto.name

class carrito_producto(models.Model):
    carrito = models.ForeignKey('carrito', on_delete=models.CASCADE)
    producto = models.ManyToManyField('productos')
    cantidad = models.IntegerField(default=1)
    precio_unitario = models.IntegerField(default=0)
    subtotal = models.IntegerField(default=0)
    
    def __str__(self):
        return self.cantidad + ' ' + self.producto.name
    
class orden(models.Model):
    estados = (
        ('pendiente', 'pendiente'),
        ('enviado', 'enviado'),
        ('entregado', 'entregado')
    )
    
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    carrito = models.ForeignKey('carrito', on_delete=models.CASCADE)
    carrito_detalle = models.ForeignKey('carrito_producto', on_delete=models.CASCADE, null=True)
    direccion = models.CharField(max_length=1000)
    fecha_envio = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20, choices=estados, default='pendiente')
    
    def __str__(self):
        return self.usuario.username + ' ' + self.estado

Hage/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
class LoginForm(forms.Form):
    usuario = forms.CharField(
        max_length=150, 
        label='Usuario', 
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label='Contraseña', 
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            self.add_error('password_confirm', "Passwords do not match")

class ProductoForm(forms.ModelForm):
    class Meta:
        model = productos
        fields = ['name', 'categoria', 'precio', 'imagen', 'activate', 'destacado']
        

Hage/views.py
from django.shortcuts import get_object_or_404, render, redirect # type: ignore
from .models import * # type: ignore
from .forms import *
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def mostrar(request):
    productos_destacados = productos.objects.filter(destacado=True)
    perfil = request.session.get('perfil')
    context = {
        'productos': productos_destacados, 
        'perfil': perfil
        }
    return render(request, 'index.html', context)


def catalogo(request):
    all_productos = productos.objects.all()
    all_categorias = categorias.objects.all()
    perfil = request.session.get('perfil')
    context = {
        'productos': all_productos, 
        'categorias': all_categorias, 
        'perfil': perfil,
        }
    return render(request, 'productos.html', context)

def nosotros(request):
    perfil = request.session.get('perfil')
    context = {
        'perfil': perfil,
        }
    return render(request, 'nosotros.html', context)

def contacto(request):
    perfil = request.session.get('perfil')
    context = {
        'perfil': perfil,
        }
    return render(request, 'contacto.html', context)

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('usuario')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_superuser:
                    login(request, user)
                    return redirect('/admin')
                else:
                    try:
                        profile = usuarios.objects.get(username=user)
                        request.session['perfil'] = profile.rol
                    except usuarios.DoesNotExist:
                        form.add_error(None, 'Perfil no encontrado para el usuario.')
                        return render(request, 'login.html', {'form': form})

                    login(request, user)
                    return redirect('index')
            else:
                form.add_error(None, 'Usuario o contraseña incorrectos, intente nuevamente')
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


def registro(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            profile = usuarios.objects.create(username=user, rol='cliente')  
            request.session['perfil'] = 'cliente'  # O el rol que corresponda
            
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'registro.html', {'form': form}) 

    
def agregar_producto(request):
    perfil = request.session.get('perfil')
    context = {
        'perfil': perfil,
        }
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud')  
    else:
        form = ProductoForm()
    context.update({'form': form})
    return render(request, 'añadir_producto.html', context)

def carritos(request):
    perfil = request.session.get('perfil')
    context = {
        'perfil': perfil,
        }
    return render(request, 'carrito.html', context)

def pago(request):
    
    perfil = request.session.get('perfil')
    context = {
        'perfil': perfil,
        }
    return render(request, 'pago.html', context)


def producto_list(request):
    perfil = request.session.get('perfil')
    context = {
        'perfil': perfil,
        }
    productos_list = productos.objects.all()
    context.update({'productos': productos_list})
    return render(request, 'crud.html', context)


def salir(request):
    logout(request)
    return redirect('index')


def modificar(request, id):
    producto = get_object_or_404(productos, pk=id)
    perfil = request.session.get('perfil')
    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            # Redirigir a otra página, por ejemplo
            return redirect('crud')
    else:
        form = ProductoForm(instance=producto)
    
    context = {
        'form': form,
        'producto': producto,# Pasar el producto al contexto
        'perfil': perfil,
    }
    return render(request, 'modificar_producto.html', context)


def eliminar(request, id):
    producto = get_object_or_404(productos, pk=id)
    producto.delete()
    return redirect('crud')

Hage/templates/añadir_producto.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="Titulo">Añadir Producto</h2>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Nombre</label>
            <input type="text" name="name" class="form-control" id="id_name" value="{{ form.name.value|default_if_none:'' }}">
            {% if form.name.errors %}
                <div class="text-danger">{{ form.name.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_categoria">Categoría</label>
            <select name="categoria" class="form-control" id="id_categoria">
                {% for categoria in form.categoria.field.queryset %}
                    <option value="{{ categoria.id }}" {% if categoria.id == form.categoria.value %}selected{% endif %}>{{ categoria.name }}</option>
                {% endfor %}
            </select>
            {% if form.categoria.errors %}
                <div class="text-danger">{{ form.categoria.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_precio">Precio</label>
            <input type="number" name="precio" class="form-control" id="id_precio" value="{{ form.precio.value|default_if_none:'' }}">
            {% if form.precio.errors %}
                <div class="text-danger">{{ form.precio.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_imagen">Imagen (URL)</label>
            <input type="text" name="imagen" class="form-control" id="id_imagen" value="{{ form.imagen.value|default_if_none:'' }}">
            {% if form.imagen.errors %}
                <div class="text-danger">{{ form.imagen.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group form-check">
            <input type="checkbox" name="activate" class="form-check-input" id="id_activate" {% if form.activate.value %}checked{% endif %}>
            <label class="form-check-label" for="id_activate">Activo</label>
            {% if form.activate.errors %}
                <div class="text-danger">{{ form.activate.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group form-check">
            <input type="checkbox" name="destacado" class="form-check-input" id="id_destacado" {% if form.destacado.value %}checked{% endif %}>
            <label class="form-check-label" for="id_destacado">Destacado</label>
            {% if form.destacado.errors %}
                <div class="text-danger">{{ form.destacado.errors }}</div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary mt-3">Añadir Producto</button>
    </form>
</div>
{% endblock %}

Hage/templates/carrito.html
{% extends "layouts/base.html"%}

{% block content%}
<h1 class="Titulo">Tu carrito</h1>
<div id='carrito'>
</div>
<div class=" text-end m-3">
    <a class="btn btn-primary btn-lg" href="{% url 'pago' %}">Proceder al Pago</a>
  </div>
{% endblock%}

Hage/templates/contacto.html
{% extends "layouts/base.html"%}

{% block content%}
<div class="container my-3 px-2 align-items-center justify-content-center col-md-7">
    <h1 class="text-center Titulo">Contacto</h1>

    <div class="card my-3">
        <div class="card-header pb-3">
            <h2 class="card-title">Numeros de contacto</h2>
        </div>
        <div class="card-content card-body row row-col-2">
            <div class="col">
                <h3>Numeros fijos:</h3>
                <p>Apoyo Agricultor</p>
                <p>+56246782359</p>
                <p>Ventas:</p>
                <p>+56246782359</p>
            </div>
            <div class="col">
                <h3>Numero moviles:</h3>
                <p>Apoyo Agricultor</p>
                <p>+56946782359</p>
                <p>Ventas:</p>
                <p>+56946782359</p>
            </div>
        </div>
        <div class="card-header pb-3 border-top">
            <h2 class="card-title">Correo de contacto</h2>
        </div>
        <div class="card-content card-body">
            <p>Soporte técnico</p>
            <p>LPatenciont@LP.cl</p>
            <p>LovePlant4ever@soporte.cl</p>
            <p>Ventas:</p>
            <p>LPventas@LP.cl</p>
        </div>
        <div class="card-header pb-3 border-top">
            <h2 class="card-title">Ubicación</h2>
        </div>
        <div class="card-content card-body row row-col-2 align-items-center">
            <div class="col">
                <p>AV.Vicuña Mackenna 6611</p>
            </div>
            <div class="col">
                <div class="iframe-container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3326.4352045741553!2d-70.60924692345259!3d-33.51606880087706!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662d065a5b819e9%3A0xc9efd4d401ef8f78!2sAv.%20Vicu%C3%B1a%20Mackenna%206611%2C%20La%20Florida%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses-419!2scl!4v1716413857699!5m2!1ses-419!2scl" 
                width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

Hage/templates/crud.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="Titulo">Lista de Productos</h2>
    <div class="table-responsive">
    <table class="table table-striped table-hover table-bordered ">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Categoría</th>
                <th>Precio</th>
                <th>Activo</th>
                <th>Destacado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td class="align-middle">{{ producto.name }}</td>
                <td class="align-middle">{{ producto.categoria.name }}</td>
                <td class="align-middle">{{ producto.precio }}</td>
                <td class="align-middle">{{ producto.activate }}</td>
                <td class="align-middle">{{ producto.destacado }}</td>
                <td class="align-middle">
                    <button type="submit" class="btn btn-primary mr-1 align-middle"> 
                        <a href="{% url 'modificar_producto' producto.id %}" class="text-white text-decoration-none">
                            Modificar
                        </a>
                    </button>
                    <form method="post" action="{% url 'eliminar_producto' producto.id %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">X</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="mx-auto">
<a href="{% url 'agregar_producto' %}" class="text-white text-decoration-none">
    <button type="submit" class="btn btn-primary mt-3" style="width: 100%;">
        agregar productos 
    </button>
</a>
</div>
</div>
{% endblock %}

Hage/templates/index.html
{% extends "layouts/base.html" %}

{% block content %}
<h1 class="Titulo">Productos Destacados</h1>

<div id="carouselExampleDark" class="carousel carousel-dark slide">
    <div class="carousel-indicators">
        {% for producto in productos %}
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="{{ forloop.counter }}" class="{% if forloop.first %}active{% endif %}" aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}"></button>
        {% endfor %}
    </div>
    <div class="carousel-inner">
        {% for producto in productos %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="10000">
                <img src="{{ producto.imagen }}" class="d-block w-100" alt="{{ producto.name }}" >
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

{% endblock %}

Hage/templates/login.html
{% extends "layouts/base.html"%}

{% block content%}
            <h5 class="card-title text-center mb-4 Titulo">Iniciar Sesión</h5>
            <form action="" method="POST">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.errors }}
                    </div>
                {% endif %}
                <div class="mb-3">
                    <label for="usuario" class="form-label">Usuario</label>
                    {{ form.usuario }}
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Contraseña</label>
                    {{ form.password }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">INICIAR SESIÓN</button>
                </div>
            </form>
            <div class="text-center mt-3">
                <a href="{% url 'register' %}">¿No tienes una cuenta? Regístrate</a>
            </div>
{% endblock%}

Hage/templates/modificar_producto.html
{% extends "layouts/base.html"%}

{% block content %}
<h2>Modificar Productos</h2>
<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Nombre</label>
        <input type="text" name="name" class="form-control" id="id_name" value="{{ form.name.value|default_if_none:'{producto.name}' }}">
        {% if form.name.errors %}
            <div class="text-danger">{{ form.name.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for ="id_categoria">Categoría</label>
        <select name="categoria" class="form-control" id="id_categoria">
            {% for categoria in form.categoria.field.queryset %}
                <option value="{{ categoria.id }}" {% if categoria.id == form.categoria.value %}selected{% endif %}>{{ categoria.name }}</option>
            {% endfor %}
        </select>
        {% if form.categoria.errors %}
            <div class="text-danger">{{ form.categoria.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="id_precio">Precio</label>
        <input type="number" name="precio" class="form-control" id="id_precio" value="{{ form.precio.value|default_if_none:'{producto.precio}' }}">
        {% if form.precio.errors %}
            <div class="text-danger">{{ form.precio.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="id_imagen">Imagen (URL)</label>
        <input type="text" name="imagen" class="form-control" id="id_imagen" value="{{ form.imagen.value|default_if_none:'{producto.imagen}' }}">
        {% if form.imagen.errors %}
            <div class="text-danger">{{ form.imagen.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group form-check">
        <input type="checkbox" name="activate" class="form-check-input" id="id_activate" {% if form.activate.value %}checked{% endif %}>
        <label class="form-check-label" for="id_activate">Activo</label>
        {% if form.activate.errors %}
            <div class="text-danger">{{ form.activate.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group form-check">
        <input type="checkbox" name="destacado" class="form-check-input" id="id_destacado" {% if form.destacado.value %}checked{% endif %}>
        <label class="form-check-label" for="id_destacado">Destacado</label>
        {% if form.destacado.errors %}
            <div class="text-danger">{{ form.destacado.errors }}</div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary mt-3">
        Guardar Cambios
    </button>
</form>

{% endblock content %}

Hage/templates/nosotros.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
<div class="container my-3 px-2 align-items-center justify-content-center col-md-7">
    <h1 class="text-center Titulo">SOBRE NOSOTROS</h1>
    <div class="mx-auto pd-auto">
        <img src="{% static 'img/logo.png' %}" class="Nosotros_imagen my-3 mx-auto d-block" width="240px">
    </div>
    <div class="card">
        <div class="card-header pb-3">
            <a class="card-title lead collapsed" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"
            style="text-decoration:none; color:rgb(118, 147, 135);">
                <b>Nosotros</b>
            </a>
            <div class="collapse multi-collapse" id="collapseExample">
                <div class="card-content card-body">
                    <p>
                        Nuestra tienda comenzó como el sueño de un amante de las plantas. 
                        Su pasión por la naturaleza lo llevó a crear una marca dedicada a expandir el acceso a una variedad de plantas para todos los posibles entusiastas. 
                        Con la apertura de nuestra tienda, nuestro objetivo es claro: queremos 
                        que todos puedan disfrutar del maravilloso mundo de las plantas.
                    </p>
                    <p>
                        Creemos que las plantas no solo son una forma de embellecer nuestros espacios, sino también una manera de conectar con la naturaleza, mejorar nuestro entorno
                        y vivir experiencias únicas. Nos dedicamos a ofrecer lo mejor en plantas, macetas y accesorios, creando espacios donde todos, desde los
                        más novatos hasta los más expertos, puedan encontrar algo que les apasione.
                    </p>
                    <p style="text-align: center; text-indent:0px;">
                        ¡Únete a nosotros y descubre un mundo de naturaleza y tranquilidad sin límites!
                    </p>
                    
                </div>
            </div>
        </div>
        <div class="card-header pb-3">
            <a class="card-title lead collapsed" data-bs-toggle="collapse" href="#collapse2" role="button" aria-expanded="false" aria-controls="collapse2"
            style="text-decoration:none; color:rgb(118, 147, 135);">
                <b>Misión</b>
            </a>
            <div class="collapse multi-collapse" id="collapse2">
                <div class="card-content card-body">
                    <p>
                        Nuestra misión es clara y apasionante: entregar productos de jardinería de calidad a precios justos. 
                        Nos dedicamos a ofrecer una amplia gama de productos que incluyen plantas, macetas y accesorios de jardinería, 
                        todos seleccionados con el máximo cuidado para garantizar la mejor experiencia.
                    </p>
                    <p>
                        Creemos firmemente en la importancia de la experiencia del usuario. Por ello, contamos con un excelente 
                        servicio de atención al cliente, dispuesto a ayudar y asesorar a nuestros clientes en todo momento. Nos
                        esforzamos por proporcionar servicios de calidad para gente de calidad, asegurando que cada interacción 
                        y cada compra sean satisfactorias y placenteras.
                    </p>
                        
                    <p>
                        Nuestro compromiso es hacer que cada amante de las plantas, desde el más novato hasta el más experto, se sienta valorado 
                        y pueda disfrutar al máximo del maravilloso mundo de la jardinería.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Hage/templates/pago.html
{% extends "layouts/base.html"%} 
{% block content %}
<div class="container mt-5">
  <h2 class="Titulo">Proceso de Pago</h2>

  <div class="row">
    <div class="col-md-6">
      <h3>Tus Productos</h3>
      <div id="carrito"></div>
    </div>

    <div class="col-md-6">
      <h3>Dirección de Envío</h3>
      <div class="form-group">
        <label for="direccion">Dirección</label>
        <input
          type="text"
          class="form-control"
          id="direccion"
          placeholder="Escribe tu dirección"
        />
      </div>

      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="envioRapido" />
        <label class="form-check-label" for="envioRapido"> Envío Rápido </label>
      </div>

      <div class="form-group mt-3">
        <label for="metodoPago">Método de Pago</label>
        <select class="form-control" id="metodoPago">
          <option value="tarjeta">Tarjeta de Crédito</option>
          <option value="paypal">PayPal</option>
          <option value="efectivo">Pago en Efectivo</option>
        </select>
      </div>

      <button type="button" class="btn btn-primary mt-2" onclick="generarBoleta()" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Realizar Pago
      </button>

      <h3 class="mt-4">Boleta</h3>
      <div id="boleta">
        <ul id="productosBoleta"></ul>
        <p id="totalBoleta"></p>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content ">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-center">
          <div>
          Lo estamos redirigiendo a la web de pago
        </div>
        <div class="spinner-border text-success" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        </div>
        <div class="modal-footer">
          <a type="button" class="text-decoration-none text-center" href="{% url 'catalogo' %}" >Cliquea en caso de no haber redireccionado</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Hage/templates/registro.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="Titulo">Register</h2>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username</label>
            <input type="text" name="username" class="form-control" id="id_username" value="{{ form.username.value|default_if_none:'' }}">
            {% if form.username.errors %}
                <div class="text-danger">{{ form.username.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_email">Email</label>
            <input type="email" name="email" class="form-control" id="id_email" value="{{ form.email.value|default_if_none:'' }}">
            {% if form.email.errors %}
                <div class="text-danger">{{ form.email.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" name="password" class="form-control" id="id_password">
            {% if form.password.errors %}
                <div class="text-danger">{{ form.password.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_password_confirm">Confirm Password</label>
            <input type="password" name="password_confirm" class="form-control" id="id_password_confirm">
            {% if form.password_confirm.errors %}
                <div class="text-danger">{{ form.password_confirm.errors }}</div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary mt-3">Register</button>
    </form>
</div>
{% endblock %}